project:
  type: website
  output-dir: docs  

website:
  title: "QTM 350"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Life Expectancy and GDP"
        href: life-gdp.qmd
      - text: "Life Expectancy and Population"
        href: life-population.qmd
      - text: "Country Analysis"
        href: country.qmd  
  page-navigation: true  

format:
  html:
    theme: cosmo

